Repository NovaNix/CS-499-Canvas-to-Paper-Tests, pull requests merged in 2025-03, with the labels that each got.

#49 Clean up existing code
  src/main/java/io/github/csgroup/quizmaker/App.java
  src/main/java/io/github/csgroup/quizmaker/qti/importing/QTIZipManager.java
  src/main/java/io/github/csgroup/quizmaker/ui/BankHostPanel.java
  src/main/java/io/github/csgroup/quizmaker/ui/BankPanel.java
  src/main/java/io/github/csgroup/quizmaker/ui/CreateBankDialog.java
  src/main/java/io/github/csgroup/quizmaker/ui/ImportQTIDialog.java
  src/main/java/io/github/csgroup/quizmaker/ui/QuestionTable.java
  src/main/java/io/github/csgroup/quizmaker/ui/RemoveBankDialog.java
  src/main/java/io/github/csgroup/quizmaker/ui/UIManager.java
  src/main/java/io/github/csgroup/quizmaker/ui/banks/BankHostPanel.java
  src/main/java/io/github/csgroup/quizmaker/ui/banks/BankPanel.java
  src/main/java/io/github/csgroup/quizmaker/ui/components/QuestionTable.java
  src/main/java/io/github/csgroup/quizmaker/ui/dialogs/CreateBankDialog.java
  src/main/java/io/github/csgroup/quizmaker/ui/dialogs/ImportQTIDialog.java
  src/main/java/io/github/csgroup/quizmaker/ui/dialogs/RemoveBankDialog.java
  src/test/java/io/github/csgroup/quizmaker/tests/QTIImportManagerTest.java
Labels: clean-up

#54 Update word skeleton
  src/main/java/io/github/csgroup/quizmaker/data/questions/WrittenResponseQuestion.java
  src/main/java/io/github/csgroup/quizmaker/word/LabelWriter.java
  src/main/java/io/github/csgroup/quizmaker/word/QuestionWriter.java
  src/main/java/io/github/csgroup/quizmaker/word/WordExporter.java
Labels: docx, core

#55 Add Quiz Datatype
  src/main/java/io/github/csgroup/quizmaker/data/Project.java
  src/main/java/io/github/csgroup/quizmaker/data/Quiz.java
  src/main/java/io/github/csgroup/quizmaker/data/events/QuizListener.java
  src/main/java/io/github/csgroup/quizmaker/data/events/quiz/QuizEvent.java
  src/main/java/io/github/csgroup/quizmaker/data/events/quiz/QuizRenameEvent.java
  src/main/java/io/github/csgroup/quizmaker/data/models/ProjectQuizListModel.java
  src/main/java/io/github/csgroup/quizmaker/data/quiz/BankSelection.java
  src/main/java/io/github/csgroup/quizmaker/data/quiz/GeneratedQuiz.java
  src/main/java/io/github/csgroup/quizmaker/utils/RandomBag.java
Labels: core

#61 Added Stores
  src/main/java/io/github/csgroup/quizmaker/data/Question.java
  src/main/java/io/github/csgroup/quizmaker/utils/stores/StoreListener.java
  src/main/java/io/github/csgroup/quizmaker/utils/stores/derived/DerivedStore.java
  src/main/java/io/github/csgroup/quizmaker/utils/stores/derived/DerivedStoreCalculator.java
  src/main/java/io/github/csgroup/quizmaker/utils/stores/readable/AbstractReadableStore.java
  src/main/java/io/github/csgroup/quizmaker/utils/stores/readable/ReadableStore.java
  src/main/java/io/github/csgroup/quizmaker/utils/stores/writable/AbstractWritableStore.java
  src/main/java/io/github/csgroup/quizmaker/utils/stores/writable/DefaultWritableStore.java
  src/main/java/io/github/csgroup/quizmaker/utils/stores/writable/WritableStore.java
  src/test/java/io/github/csgroup/quizmaker/testingutils/GCUtils.java
  src/test/java/io/github/csgroup/quizmaker/tests/stores/DerivedStoreTests.java
Labels: ui, core

#63 Add Quiz Generation
  src/main/java/io/github/csgroup/quizmaker/data/Answer.java
  src/main/java/io/github/csgroup/quizmaker/data/Question.java
  src/main/java/io/github/csgroup/quizmaker/data/QuestionBank.java
  src/main/java/io/github/csgroup/quizmaker/data/Quiz.java
  src/main/java/io/github/csgroup/quizmaker/data/answers/BlankAnswer.java
  src/main/java/io/github/csgroup/quizmaker/data/answers/MatchingAnswer.java
  src/main/java/io/github/csgroup/quizmaker/data/answers/SimpleAnswer.java
  src/main/java/io/github/csgroup/quizmaker/data/questions/FillInTheBlankQuestion.java
  src/main/java/io/github/csgroup/quizmaker/data/questions/MatchingQuestion.java
  src/main/java/io/github/csgroup/quizmaker/data/questions/MultipleChoiceQuestion.java
  src/main/java/io/github/csgroup/quizmaker/data/questions/WrittenResponseQuestion.java
  src/main/java/io/github/csgroup/quizmaker/data/quiz/BankSelection.java
  src/main/java/io/github/csgroup/quizmaker/data/quiz/GeneratedQuiz.java
  src/main/java/io/github/csgroup/quizmaker/utils/RandomBag.java
  src/main/java/io/github/csgroup/quizmaker/word/WordExporter.java
Labels: core

#60 Add Temporary QTI return
  src/main/java/io/github/csgroup/quizmaker/data/Question.java
  src/main/java/io/github/csgroup/quizmaker/data/answers/BlankAnswer.java
  src/main/java/io/github/csgroup/quizmaker/data/answers/MatchingAnswer.java
  src/main/java/io/github/csgroup/quizmaker/data/questions/FillInTheBlankQuestion.java
  src/main/java/io/github/csgroup/quizmaker/data/questions/MatchingQuestion.java
  src/main/java/io/github/csgroup/quizmaker/data/questions/MultipleChoiceQuestion.java
  src/main/java/io/github/csgroup/quizmaker/data/questions/WrittenResponseQuestion.java
  src/main/java/io/github/csgroup/quizmaker/data/quiz/BankSelection.java
  src/main/java/io/github/csgroup/quizmaker/qti/QTIReader.java
Labels: qti

#64 HTML and Basic Label Writing
  .gitignore
  pom.xml
  src/main/java/io/github/csgroup/quizmaker/App.java
  src/main/java/io/github/csgroup/quizmaker/word/LabelWriter.java
  src/main/java/io/github/csgroup/quizmaker/word/QuestionWriter.java
  src/main/java/io/github/csgroup/quizmaker/word/WordExporter.java
  src/test/resources/testImage.JPG
Labels: enhancement, docx
